- name: Standalone Physical (vCMP) Unmanaged Mode BIG-IP setup
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - variable.yaml

  tasks:

  - include_tasks: ../common/onboarding.yaml 
      bigip_ip="{{vcmp_guest_bigip_ip}}"
      bigip_username="{{vcmp_guest_bigip_username}}"
      bigip_password="{{vcmp_guest_bigip_password}}"
    when: '"yes" in onboarding '

  - name: Add VLAN(s) on vCMP host
    bigip_vlan:
      server: "{{vcmp_host_bigip_ip}}"
      user: "{{ vcmp_host_bigip_username }}"
      password: "{{ vcmp_host_bigip_password }}"
      name: "{{tenant_name_aci}}_{{item.name}}"
      tag: "{{item.id}}"
      tagged_interfaces:
      - "{{item.interface}}"
      validate_certs: "no"
    with_items: "{{vlan_information}}"

  - name: Assign VLAN to vCMP guests
    bigip_vcmp_guest:
      server: "{{vcmp_host_bigip_ip}}"
      user: "{{ vcmp_host_bigip_username }}"
      password: "{{ vcmp_host_bigip_password }}"
      name: "{{vcmp_guest_name}}"
      vlans:
       - "{{tenant_name_aci}}_{{vlan_information[0]['name']}}"
       - "{{tenant_name_aci}}_{{vlan_information[1]['name']}}"
      validate_certs: False
    with_items: "{{vlan_information}}"
    delegate_to: localhost

  - name: Add SELF-IP(s) on vCMP guest
    bigip_selfip: 
     server: "{{vcmp_guest_bigip_ip}}"
     user: "{{ vcmp_guest_bigip_username }}"
     password: "{{ vcmp_guest_bigip_password }}"
     name: "{{tenant_name_aci}}_{{item.name}}"
     address: "{{item.address}}"
     netmask: "{{item.netmask}}"
     vlan: "{{tenant_name_aci}}_{{item.vlan}}"
     validate_certs: "no"
    with_items: "{{ bigip_selfip_information }}"

  - name: Add route(s) on vCMP guest
    bigip_static_route:
      server: "{{vcmp_guest_bigip_ip}}"
      user: "{{ vcmp_guest_bigip_username }}"
      password: "{{ vcmp_guest_bigip_password }}"
      name: "{{item.name}}"
      gateway_address: "{{item.gw_address}}"
      netmask: "{{item.netmask}}"
      destination: "{{item.destination}}" 
      validate_certs: "no"
    with_items: "{{static_route}}"
    delegate_to: localhost

  - include_tasks: ../common/http_service.yaml 
      bigip_ip="{{vcmp_guest_bigip_ip}}" 
      bigip_username="{{vcmp_guest_bigip_username}}"
       bigip_password="{{vcmp_guest_bigip_password}}"
    when: '"yes" in service '
