- name: Cleanup BIG-IP  
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - include_tasks: ../common/http_service_cleanup.yaml
      bigip_ip="{{bigip1_ip}}"
      bigip_username="{{bigip1_username}}"
      bigip_password="{{bigip1_password}}"

  - name: Delete route(s) on BIG-IP1
    bigip_static_route:
      server: "{{bigip1_ip}}"
      user: "{{ bigip1_username }}"
      password: "{{ bigip1_password }}"
      name: "{{static_route_name}}"
      state: absent
      validate_certs: "no"
    delegate_to: localhost
    
  - name: Delete SELF-IP(s) on BIG-IP1
    bigip_selfip:
     server: "{{bigip1_ip}}"
     user: "{{ bigip1_username }}"
     password: "{{ bigip1_password }}"
     name: "{{tenant_name}}_{{bigip1_selfip_name}}"
     state: absent
     validate_certs: "no"

  - name: Delete VLAN(s) on BIG-IP1
    bigip_vlan:
      server: "{{bigip1_ip}}"
      user: "{{ bigip1_username }}"
      password: "{{ bigip1_password }}"
      name: "{{tenant_name}}_{{vlan_name}}"
      state: absent
      validate_certs: "no"
