- name: ACI
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
   - ../common/ip_mapping.yml

  tasks:

  - name: Get BIG-IP name from a Physical Logical Device Cluster
    aci_rest:
      action: "get"
      uri: "/api/node/mo/uni/tn-{{tenant_name}}/lDevVip-{{logicalDeviceCluster_name}}.json?query-target=subtree&target-subtree-class=vnsCDev"
      host: "{{apic_ip}}"
      username: "{{apic_username}}"
      password: "{{apic_password}}"
      validate_certs: "false"
    register: cdev

  - name: Assign the BIG-IP name to a variable
    set_fact:
     bigip_name: "{{(cdev.imdata[0]['vnsCDev']['attributes']['vmName'])}}"

  - name: Get BIG-IP Address
    set_fact:
     bigip_ip: "{{item.address}}"
     bigip_username: "{{item.username}}"
     bigip_password: "{{item.password}}"
    when: 'item.name in bigip_name'
    with_items: "{{mapping}}"

  - name: Display the BIG-IP Address
    debug: msg="{{bigip_name}} -> {{bigip_ip}} , {{bigip_username}} , {{bigip_password}}"
    
  - name: Enable/Disable pool members
    bigip_pool_member:
      server: "{{ bigip_ip }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      name: "{{pool_member_name}}"
      port: "{{pool_member_port}}"
      pool: "{{pool_name}}"
      session_state: "{{pool_member_state}}"
      monitor_state: "{{pool_member_state}}"
      validate_certs: False
    delegate_to: localhost
